version: "3"
services:
  backend:
    build: backend
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_USER=
      - MYSQL_HOST=
      - MYSQL_DATABASE=
      - MYSQL_PASSWORD=
  frontend:
    build: frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      API_PROXY_PASS: backend
  db:
    image: mysql
    restart: always
    env_file:
      - .env
